import { OverviewResponseData } from '../overview';
import { projectResponseData } from '../../project/__mocks__/project_response_data';
import { toolResponseData } from '../../tool/__mocks__/tool_response_data';
import { mockResponseNodes } from '../../../../lib/test/mock_response_nodes';

type Project = OverviewResponseData['projects'][0];
type Tool = OverviewResponseData['tools'][0];

/**
 * Mocks an OverviewResponseData type.
 * @param projects An optional array of OverviewResponseData projects.  These
 * will be used in place of the projects generated by default.
 * @param tools An optional array of OverviewResponseData tools.  These will be
 * used in place of the tools generated by default.
 * @return A mocked OverviewResponseData type.
 */
export function overviewResponseData (
  projects: Project[] = mockResponseNodes(projectResponseData),
  tools: Tool[] = mockResponseNodes(toolResponseData)
): OverviewResponseData {
  return { projects, tools };
}
